# Generated by Django 4.1.4 on 2023-01-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='members',
        ),
    ]
