# Generated by Django 4.1.4 on 2023-01-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('marks', models.CharField(max_length=255)),
            ],
        ),
    ]
